package com.daCheng.lectotype.domain.excel;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.RichTextString;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.ss.util.CellRangeAddress;

import com.daCheng.lectotype.domain.ValveSpecification;
import com.daCheng.lectotype.service.ValveSpecificationService;

public class ExcelBuilder {
	
	
	private void buildSheet(Workbook wb,ValveSpecification valveSpecification){
		Sheet sheet = wb.createSheet();
		sheet.setColumnWidth(0,10 * 256);
		sheet.setColumnWidth(1,14 * 256);
		sheet.setColumnWidth(2,5 * 256);
		sheet.setColumnWidth(3,(int) (11.5 * 256));
		sheet.setColumnWidth(4,(int) (8.5 * 256));
		sheet.setColumnWidth(5,10 * 256);
		sheet.setColumnWidth(6,(int) (8.5 * 256));
		sheet.setColumnWidth(7,(int) (8.5 * 256));
		sheet.setColumnWidth(8,(int) (7.5 * 256));
				
		Font font1 = wb.createFont();
		font1.setFontHeightInPoints((short)9);
		font1.setFontName("宋体");		
		CellStyle cellStyle1 = wb.createCellStyle(); 
		cellStyle1.setFont(font1);
		
		Font font9 = wb.createFont();
		font9.setFontHeightInPoints((short)9);
		font9.setFontName("宋体");		
		CellStyle cellStyle9 = wb.createCellStyle(); 
		cellStyle9.setFont(font9);
		cellStyle9.setAlignment(CellStyle.ALIGN_CENTER);
		
		Font font2 = wb.createFont();
		font2.setFontHeightInPoints((short)9);
		font2.setFontName("宋体");
		font2.setBoldweight(Font.BOLDWEIGHT_BOLD);		
		CellStyle cellStyle2 = wb.createCellStyle(); 
		cellStyle2.setFont(font2);
		cellStyle2.setAlignment(CellStyle.ALIGN_CENTER);
		
		Font font3 = wb.createFont();
		font3.setFontHeightInPoints((short)13);
		font3.setFontName("Times New Roman");
		font3.setBoldweight(Font.BOLDWEIGHT_BOLD);		
		CellStyle cellStyle3 = wb.createCellStyle(); 
		cellStyle3.setFont(font3);
		cellStyle3.setAlignment(CellStyle.ALIGN_CENTER);
		
		Font font4 = wb.createFont();
		font4.setFontHeightInPoints((short)14);
		font4.setFontName("宋体");
		font4.setBoldweight(Font.BOLDWEIGHT_BOLD);		
		CellStyle cellStyle4 = wb.createCellStyle(); 
		cellStyle4.setFont(font4);
		cellStyle4.setAlignment(CellStyle.ALIGN_CENTER);
		
		Font font5 = wb.createFont();
		font5.setFontHeightInPoints((short)12);
		font5.setFontName("Times New Roman");
		CellStyle cellStyle5 = wb.createCellStyle(); 
		cellStyle5.setFont(font5);
		cellStyle5.setAlignment(CellStyle.ALIGN_CENTER);
		
		Font font6 = wb.createFont();
		font6.setFontHeightInPoints((short)16);
		font6.setFontName("黑体");
		font6.setBoldweight(Font.BOLDWEIGHT_BOLD);		
		CellStyle cellStyle6 = wb.createCellStyle(); 
		cellStyle6.setFont(font6);
		cellStyle6.setAlignment(CellStyle.ALIGN_CENTER);
		cellStyle6.setWrapText(true);
		
		Font font7 = wb.createFont();
		font7.setFontHeightInPoints((short)9);
		font7.setFontName("Times New Roman");
		CellStyle cellStyle7 = wb.createCellStyle(); 
		cellStyle7.setFont(font7);
		cellStyle7.setAlignment(CellStyle.ALIGN_CENTER);		
		
		Font font8 = wb.createFont();
		font8.setFontHeightInPoints((short)12);
		font8.setFontName("宋体");
		CellStyle cellStyle8 = wb.createCellStyle(); 
		cellStyle8.setFont(font8);
		cellStyle8.setAlignment(CellStyle.ALIGN_CENTER);
		
		Row row = sheet.createRow(0);
		row.setHeightInPoints((float) 24.75);
		Cell cell = row.createCell(0);
		cell.setCellStyle(cellStyle3);
		cell.setCellValue("DA CHENG");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle6);
		String str = "气动调节阀计算选型表PNEUMATIC  CONTROL  VALVE";
		RichTextString richTextString = wb.getCreationHelper().createRichTextString(str);
		richTextString.applyFont(10, str.length(), font7);
		cell.setCellValue(richTextString);
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("项目名称");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle8);
		cell.setCellValue(valveSpecification.getProjectName());
		
		row = sheet.createRow(1);
		row.setHeightInPoints((float) 24.75);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle4);
		cell.setCellValue("上  海  大  成  仪 表 厂");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("Project");
		
		row = sheet.createRow(2);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle5);
		cell.setCellValue("Shanghai        Dacheng");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle7);
		cell.setCellValue("CALCULATION  SPECIFICATION");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("第1页");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("共1页");
		
		row = sheet.createRow(3);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle5);
		cell.setCellValue("Instrument      Factory");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("P.1");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("of 1");
		
		row = sheet.createRow(4);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("位号 Tag No");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getTagNo());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle2);
		cell.setCellValue("执行机构   Actuator");
		
		row = sheet.createRow(5);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("数量 Quantity");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getQuantity());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("型号 Model");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getActuator().getModel());
		
		row = sheet.createRow(6);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("用途 Service");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getService());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("动作形式 Action");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getActuator().getAction());

		
		row = sheet.createRow(7);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle2);
		cell.setCellValue("工艺参数  Process  Parameter");
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("弹簧范围  Spring R. kPa");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getActuator().getSpringRange());
		
		row = sheet.createRow(8);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("管道尺寸/材质 Pipe Size/Material");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getPipeSizeAndMaterial());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("供气压力  Air Press. Mpa");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getActuator().getAirPressure());
		
		row = sheet.createRow(9);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("介质名称 Fluid Name");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getFluidName());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("气源接头  Air Conn. Size");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getActuator().getAirConnection());
		
		row = sheet.createRow(10);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("介质状态 Fluid State");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getFluidState());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle2);
		cell.setCellValue("附  件    Accessories");
		
		row = sheet.createRow(11);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("密度 ρ  Density  kg/m3");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getDensity());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("定位器");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("型号Model");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getPositioner().getModel());
						
		row = sheet.createRow(12);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("流量");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("□气体 Gas Nm3 /h");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("Qmax");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getQmax());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("输入信号  Input Sig.mA");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getPositioner().getInputSignal());
		
		row = sheet.createRow(13);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Q");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("□蒸汽 Vapor kg/h");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("Qnor");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getQnor());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("供气压力Air Press. Mpa");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getPositioner().getAirPressure());
		
		row = sheet.createRow(14);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Flow");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("□液体 Liquid Nm3/h");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("Qmin");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getQmin());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("信号接口 Sig. Conn.");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getPositioner().getSignalConnection());
		
		row = sheet.createRow(15);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("操作温度    Oper. Temperature ℃");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getOperationTemperature());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Positioner");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("气接口尺寸 Air Conn.");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getPositioner().getAirConnectionSize());
		
		row = sheet.createRow(16);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("阀前压力P1  Upstream Press. Mpa");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getUpstreamPressure());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("防爆等级   Exp. Class");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getPositioner().getExplosionProof());
		
		row = sheet.createRow(17);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("阀后压力P2  Downstream Press. Mpa");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getDownstreamPressure());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("电磁阀");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("型号 Model");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getSolenoid().getModel());
		
		row = sheet.createRow(18);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("关闭时最大压差ΔP  Diff. Press. Mpa");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getDifferentialPressure());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("电源电压 Supply Power.v");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getSolenoid().getSupplyPower());
		
		row = sheet.createRow(19);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("运动粘度γ  Dynamic Viscosity mm2/s");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getDynamicViscosity());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("电源接口 Power Conn.");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getSolenoid().getPowerConnection());
		
		row = sheet.createRow(20);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("压缩系数 Z   Compress Factor");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getCompressFactor());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Solenoid");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("气接口尺寸 Air Conn.");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getSolenoid().getAirConnection());
				
		row = sheet.createRow(21);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("汽化压力 Pv  Vapor Press.  100kPa");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getVaporPressure());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("防爆等级   Exp. Class");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getSolenoid().getExplosionProof());
		
		row = sheet.createRow(22);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("临界压力 Pc  Critical Press.  100kPa");
		cell = row.createCell(3);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getProcessPara().getCriticalPressure());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("阀位开关");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("型号 Model");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getLimitSwitch().getModel());
				
		row = sheet.createRow(23);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle2);
		cell.setCellValue("计  算     Calculation");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("接点型式  Joint Model");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getLimitSwitch().getJointModel());
		
		row = sheet.createRow(24);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("计算流量系数");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Kv max");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getCalculation().getKvmax());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Limit");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("接口尺寸  Conn. Size");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getLimitSwitch().getConnectionSize());
		
		row = sheet.createRow(25);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("Calculated Kv");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Kv min");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getCalculation().getKvmin());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Switch");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("防爆等级  Exp. Class");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getLimitSwitch().getExplosionProof());
		
		row = sheet.createRow(26);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("选用流量系数 Selected  Kv");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getCalculation().getSelectedKv());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("阀位传送器");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("型号 Model");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getConveyer().getModel());
		
		row = sheet.createRow(27);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("阀开度 %");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("K max");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getCalculation().getKmax());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("输出信号 Output Sig.mA");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getConveyer().getOutputSignal());
		
		row = sheet.createRow(28);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("Travel");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("K min");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getCalculation().getKmin());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Conveyer");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("接口尺寸 Conn. Size");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getConveyer().getConnectionSize());
				
		row = sheet.createRow(29);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("噪声估算  Noise Level dBA");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getCalculation().getNoiseLevel());
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("防爆等级  Exp. Class");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getConveyer().getExplosionProof());
		
		row = sheet.createRow(30);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle2);
		cell.setCellValue("调节阀选型    Selected Model");
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("过滤减压阀");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("型号 Model");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getFilterReducingValve().getModel());
		
		row = sheet.createRow(31);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("名称 Name");
		cell = row.createCell(1);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getName());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue("Reg.");
		cell = row.createCell(5);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("接口 Conn.");
		cell = row.createCell(7);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().getFilterReducingValve().getConnection());
				
		row = sheet.createRow(32);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("型号   Valve Model");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getModel());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("手轮机构  Hand Wheel");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getAccessory().isHandWheel());
		
		row = sheet.createRow(33);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("通径/阀座DN/dN Val./Seat mm");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getDiameterNominal() + "/" + valveSpecification.getSelectedModel().getSeatDiameter());
		
		row = sheet.createRow(34);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("公称压力PN Nominal Pressure  Mpa");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getNominalPressure());
		
		row = sheet.createRow(35);
		
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("流开/流闭  Flow Open/Close");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getFlowOpenClose());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle2);
		cell.setCellValue("备  注   Remarks");
		
		row = sheet.createRow(36);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("失气位置  Air Fail Valve Position");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getAirFail());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getRemarks());
		
		row = sheet.createRow(37);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("流量特性  Flow Character");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getFlowCharacter());
		
		row = sheet.createRow(38);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("阀体材质  Body Material");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getBodyMaterial());
		
		row = sheet.createRow(39);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("阀座材质  Seat Material");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getSeatMaterial());
		
		row = sheet.createRow(40);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("阀芯材质  Plug Material");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getPlugMaterial());
		
		row = sheet.createRow(41);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("填料      Packing");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getPacking());
		
		row = sheet.createRow(42);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("上阀盖形式   Bonnet Type");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getBonnetType());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("选型 Desd.");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("日期 Date");
				
		row = sheet.createRow(43);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("连接法兰标准 Conn. Flange");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getConnectionFlange());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("校对 Chkd.");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("日期 Date");
		
		row = sheet.createRow(44);
		row.setHeightInPoints(15);
		cell = row.createCell(0);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("泄漏等级     Leakage Class");
		cell = row.createCell(2);
		cell.setCellStyle(cellStyle9);
		cell.setCellValue(valveSpecification.getSelectedModel().getLeakageClass());
		cell = row.createCell(4);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("审核 Appd.");
		cell = row.createCell(6);
		cell.setCellStyle(cellStyle1);
		cell.setCellValue("日期 Date");
		

		
		sheet.addMergedRegion(new CellRangeAddress(0,0,0,2));
		sheet.addMergedRegion(new CellRangeAddress(0,1,3,5));
		sheet.addMergedRegion(new CellRangeAddress(0,1,7,8));
		sheet.addMergedRegion(new CellRangeAddress(1,1,0,2));
		sheet.addMergedRegion(new CellRangeAddress(2,2,0,2));
		sheet.addMergedRegion(new CellRangeAddress(2,2,3,5));
		sheet.addMergedRegion(new CellRangeAddress(2,2,7,8));
		sheet.addMergedRegion(new CellRangeAddress(3,3,0,2));
		sheet.addMergedRegion(new CellRangeAddress(3,3,3,5));
		sheet.addMergedRegion(new CellRangeAddress(3,3,7,8));
		sheet.addMergedRegion(new CellRangeAddress(4,4,1,3));
		sheet.addMergedRegion(new CellRangeAddress(4,4,4,8));
		sheet.addMergedRegion(new CellRangeAddress(5,5,1,3));
		sheet.addMergedRegion(new CellRangeAddress(5,5,4,5));
		sheet.addMergedRegion(new CellRangeAddress(5,5,6,8));
		sheet.addMergedRegion(new CellRangeAddress(6,6,1,3));
		sheet.addMergedRegion(new CellRangeAddress(6,6,4,5));
		sheet.addMergedRegion(new CellRangeAddress(6,6,6,8));
		sheet.addMergedRegion(new CellRangeAddress(7,7,0,3));
		sheet.addMergedRegion(new CellRangeAddress(7,7,4,5));
		sheet.addMergedRegion(new CellRangeAddress(7,7,6,8));
		sheet.addMergedRegion(new CellRangeAddress(8,8,0,1));
		sheet.addMergedRegion(new CellRangeAddress(8,8,2,3));
		sheet.addMergedRegion(new CellRangeAddress(8,8,4,5));
		sheet.addMergedRegion(new CellRangeAddress(8,8,6,8));
		sheet.addMergedRegion(new CellRangeAddress(9,9,0,1));
		sheet.addMergedRegion(new CellRangeAddress(9,9,2,3));
		sheet.addMergedRegion(new CellRangeAddress(9,9,4,5));
		sheet.addMergedRegion(new CellRangeAddress(9,9,6,8));
		sheet.addMergedRegion(new CellRangeAddress(10,10,0,1));
		sheet.addMergedRegion(new CellRangeAddress(10,10,2,3));
		sheet.addMergedRegion(new CellRangeAddress(10,10,4,8));
		sheet.addMergedRegion(new CellRangeAddress(11,11,0,1));
		sheet.addMergedRegion(new CellRangeAddress(11,11,2,3));
		sheet.addMergedRegion(new CellRangeAddress(11,12,4,4));
		sheet.addMergedRegion(new CellRangeAddress(11,11,5,6));
		sheet.addMergedRegion(new CellRangeAddress(11,11,7,8));
		sheet.addMergedRegion(new CellRangeAddress(12,12,5,6));
		sheet.addMergedRegion(new CellRangeAddress(12,12,7,8));
		sheet.addMergedRegion(new CellRangeAddress(13,14,4,4));
		sheet.addMergedRegion(new CellRangeAddress(13,13,5,6));
		sheet.addMergedRegion(new CellRangeAddress(13,13,7,8));
		sheet.addMergedRegion(new CellRangeAddress(14,14,5,6));
		sheet.addMergedRegion(new CellRangeAddress(14,14,7,8));
		sheet.addMergedRegion(new CellRangeAddress(15,15,0,2));
		sheet.addMergedRegion(new CellRangeAddress(15,16,4,4));
		sheet.addMergedRegion(new CellRangeAddress(15,15,5,6));
		sheet.addMergedRegion(new CellRangeAddress(15,15,7,8));
		sheet.addMergedRegion(new CellRangeAddress(16,16,0,2));
		sheet.addMergedRegion(new CellRangeAddress(16,16,5,6));
		sheet.addMergedRegion(new CellRangeAddress(16,16,7,8));
		sheet.addMergedRegion(new CellRangeAddress(17,17,0,2));
		sheet.addMergedRegion(new CellRangeAddress(17,18,4,4));
		sheet.addMergedRegion(new CellRangeAddress(17,17,5,6));
		sheet.addMergedRegion(new CellRangeAddress(17,17,7,8));
		sheet.addMergedRegion(new CellRangeAddress(18,18,0,2));
		sheet.addMergedRegion(new CellRangeAddress(18,18,5,6));
		sheet.addMergedRegion(new CellRangeAddress(18,18,7,8));
		sheet.addMergedRegion(new CellRangeAddress(19,19,0,2));
		sheet.addMergedRegion(new CellRangeAddress(19,19,5,6));
		sheet.addMergedRegion(new CellRangeAddress(19,19,7,8));
		sheet.addMergedRegion(new CellRangeAddress(20,20,0,2));
		sheet.addMergedRegion(new CellRangeAddress(20,21,4,4));
		sheet.addMergedRegion(new CellRangeAddress(20,20,5,6));
		sheet.addMergedRegion(new CellRangeAddress(20,20,7,8));
		sheet.addMergedRegion(new CellRangeAddress(21,21,0,2));
		sheet.addMergedRegion(new CellRangeAddress(21,21,5,6));
		sheet.addMergedRegion(new CellRangeAddress(21,21,7,8));
		sheet.addMergedRegion(new CellRangeAddress(22,22,0,2));
		sheet.addMergedRegion(new CellRangeAddress(22,23,4,4));
		sheet.addMergedRegion(new CellRangeAddress(22,22,5,6));
		sheet.addMergedRegion(new CellRangeAddress(22,22,7,8));
		sheet.addMergedRegion(new CellRangeAddress(23,23,0,3));
		sheet.addMergedRegion(new CellRangeAddress(23,23,5,6));
		sheet.addMergedRegion(new CellRangeAddress(23,23,7,8));
		sheet.addMergedRegion(new CellRangeAddress(24,24,2,3));
		sheet.addMergedRegion(new CellRangeAddress(24,24,5,6));
		sheet.addMergedRegion(new CellRangeAddress(24,24,7,8));
		sheet.addMergedRegion(new CellRangeAddress(25,25,2,3));
		sheet.addMergedRegion(new CellRangeAddress(25,25,5,6));
		sheet.addMergedRegion(new CellRangeAddress(25,25,7,8));
		sheet.addMergedRegion(new CellRangeAddress(26,26,0,1));
		sheet.addMergedRegion(new CellRangeAddress(26,26,2,3));
		sheet.addMergedRegion(new CellRangeAddress(26,27,4,4));
		sheet.addMergedRegion(new CellRangeAddress(26,26,5,6));
		sheet.addMergedRegion(new CellRangeAddress(26,26,7,8));
		sheet.addMergedRegion(new CellRangeAddress(27,27,2,3));
		sheet.addMergedRegion(new CellRangeAddress(27,27,5,6));
		sheet.addMergedRegion(new CellRangeAddress(27,27,7,8));
		sheet.addMergedRegion(new CellRangeAddress(28,28,2,3));
		sheet.addMergedRegion(new CellRangeAddress(28,28,5,6));
		sheet.addMergedRegion(new CellRangeAddress(28,28,7,8));
		sheet.addMergedRegion(new CellRangeAddress(29,29,0,1));
		sheet.addMergedRegion(new CellRangeAddress(29,29,2,3));
		sheet.addMergedRegion(new CellRangeAddress(29,29,5,6));
		sheet.addMergedRegion(new CellRangeAddress(29,29,7,8));
		sheet.addMergedRegion(new CellRangeAddress(30,30,0,3));
		sheet.addMergedRegion(new CellRangeAddress(30,30,5,6));
		sheet.addMergedRegion(new CellRangeAddress(30,30,7,8));
		sheet.addMergedRegion(new CellRangeAddress(31,31,1,3));
		sheet.addMergedRegion(new CellRangeAddress(31,31,5,6));
		sheet.addMergedRegion(new CellRangeAddress(31,31,7,8));
		sheet.addMergedRegion(new CellRangeAddress(32,32,0,1));
		sheet.addMergedRegion(new CellRangeAddress(32,32,2,3));
		sheet.addMergedRegion(new CellRangeAddress(32,32,4,5));
		sheet.addMergedRegion(new CellRangeAddress(32,32,6,8));
		sheet.addMergedRegion(new CellRangeAddress(33,33,0,1));
		sheet.addMergedRegion(new CellRangeAddress(33,33,2,3));
		sheet.addMergedRegion(new CellRangeAddress(33,33,4,8));
		sheet.addMergedRegion(new CellRangeAddress(34,34,0,1));
		sheet.addMergedRegion(new CellRangeAddress(34,34,2,3));
		sheet.addMergedRegion(new CellRangeAddress(34,34,4,8));
		sheet.addMergedRegion(new CellRangeAddress(35,35,0,1));
		sheet.addMergedRegion(new CellRangeAddress(35,35,2,3));
		sheet.addMergedRegion(new CellRangeAddress(35,35,4,8));
		sheet.addMergedRegion(new CellRangeAddress(36,36,0,1));
		sheet.addMergedRegion(new CellRangeAddress(36,36,2,3));
		sheet.addMergedRegion(new CellRangeAddress(36,41,4,8));
		sheet.addMergedRegion(new CellRangeAddress(36,36,0,1));
		sheet.addMergedRegion(new CellRangeAddress(36,36,2,3));
		sheet.addMergedRegion(new CellRangeAddress(37,37,0,1));
		sheet.addMergedRegion(new CellRangeAddress(37,37,2,3));
		sheet.addMergedRegion(new CellRangeAddress(38,38,0,1));
		sheet.addMergedRegion(new CellRangeAddress(38,38,2,3));
		sheet.addMergedRegion(new CellRangeAddress(39,39,0,1));
		sheet.addMergedRegion(new CellRangeAddress(39,39,2,3));
		sheet.addMergedRegion(new CellRangeAddress(40,40,0,1));
		sheet.addMergedRegion(new CellRangeAddress(40,40,2,3));
		sheet.addMergedRegion(new CellRangeAddress(41,41,0,1));
		sheet.addMergedRegion(new CellRangeAddress(41,41,2,3));
		sheet.addMergedRegion(new CellRangeAddress(42,42,0,1));
		sheet.addMergedRegion(new CellRangeAddress(42,42,2,3));
		sheet.addMergedRegion(new CellRangeAddress(42,42,7,8));
		sheet.addMergedRegion(new CellRangeAddress(43,43,0,1));
		sheet.addMergedRegion(new CellRangeAddress(43,43,2,3));
		sheet.addMergedRegion(new CellRangeAddress(43,43,7,8));
		sheet.addMergedRegion(new CellRangeAddress(44,44,0,1));
		sheet.addMergedRegion(new CellRangeAddress(44,44,2,3));
		sheet.addMergedRegion(new CellRangeAddress(44,44,7,8));
		
		
	}
	
	public static void main(String[] args){
//		File xlsFile = new File("f:\\xlsFile");
		Workbook wb = new HSSFWorkbook();			
			
//		wb = WorkbookFactory.create(xlsFile);
		ValveSpecificationService service = new ValveSpecificationService();
		
		ExcelBuilder builder = new ExcelBuilder();
		builder.buildSheet(wb,service.getValveSpecification("1388559233785"));
		try{
			FileOutputStream fileOut = new FileOutputStream("f:/workbook.xls");
			wb.write(fileOut);
			fileOut.close();
		}catch(Exception e){
			e.printStackTrace();
		}



	}
	
}
